- name: Modify root password and expiration time
  hosts: localhost
  become: yes
  tasks:
    - name: Change root password
      user:
        name: root
        password: "{{ 123 | password_hash('sha512') }}"
        update_password: always
      vars:
        new_password: "your_new_secure_password"

    - name: Set root password expiration time
      shell: "chage -M 90 root"
