- hosts: node1
  tasks:
  - name: Change root password
    user:
      name: root
      update_password: always
      password: "{{ 123 }}"
  - name: Change root password expiration time
    shell: chage -M {{ 30 }} root
